//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyUnit.extra.cs files to add code to generated quantities.
//     Add Extensions\MyUnitExtensions.cs to decorate quantities with new behavior.
//     Add UnitDefinitions\MyUnit.json and run GeneratUnits.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Copyright (c) 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com).
// https://github.com/angularsen/UnitsNet
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

using System;
using UnitsNet.InternalHelpers.Calculators;

// Windows Runtime Component does not support extension methods and method overloads: https://msdn.microsoft.com/en-us/library/br230301.aspx
#if !WINDOWS_UWP
namespace UnitsNet.Extensions.NumberToRotationalSpeed
{
    public static class NumberToRotationalSpeedExtensions
    {
        #region CentiradianPerSecond

        /// <inheritdoc cref="RotationalSpeed.FromCentiradiansPerSecond(double)"/>
        public static RotationalSpeed CentiradiansPerSecond(this int value) => (RotationalSpeed)RotationalSpeed.FromCentiradiansPerSecond(value);
	
        /// <inheritdoc cref="RotationalSpeed.FromCentiradiansPerSecond(double)"/>
        public static RotationalSpeed CentiradiansPerSecond(this long value) => (RotationalSpeed)RotationalSpeed.FromCentiradiansPerSecond(value);

        /// <inheritdoc cref="RotationalSpeed.FromCentiradiansPerSecond(double)"/>
        public static RotationalSpeed CentiradiansPerSecond(this double value) => (RotationalSpeed)RotationalSpeed.FromCentiradiansPerSecond(new Number<double, DoubleCalculator>(value));

        /// <inheritdoc cref="RotationalSpeed.FromCentiradiansPerSecond(double)"/>
        public static RotationalSpeed CentiradiansPerSecond(this float value) => (RotationalSpeed)RotationalSpeed.FromCentiradiansPerSecond(value);

        /// <inheritdoc cref="RotationalSpeed.FromCentiradiansPerSecond(double)"/>
        public static RotationalSpeed CentiradiansPerSecond(this decimal value) => (RotationalSpeed)RotationalSpeed.FromCentiradiansPerSecond(new Number<double, DoubleCalculator>(Decimal.ToDouble(value)));

        #endregion

        #region DeciradianPerSecond

        /// <inheritdoc cref="RotationalSpeed.FromDeciradiansPerSecond(double)"/>
        public static RotationalSpeed DeciradiansPerSecond(this int value) => (RotationalSpeed)RotationalSpeed.FromDeciradiansPerSecond(value);
	
        /// <inheritdoc cref="RotationalSpeed.FromDeciradiansPerSecond(double)"/>
        public static RotationalSpeed DeciradiansPerSecond(this long value) => (RotationalSpeed)RotationalSpeed.FromDeciradiansPerSecond(value);

        /// <inheritdoc cref="RotationalSpeed.FromDeciradiansPerSecond(double)"/>
        public static RotationalSpeed DeciradiansPerSecond(this double value) => (RotationalSpeed)RotationalSpeed.FromDeciradiansPerSecond(new Number<double, DoubleCalculator>(value));

        /// <inheritdoc cref="RotationalSpeed.FromDeciradiansPerSecond(double)"/>
        public static RotationalSpeed DeciradiansPerSecond(this float value) => (RotationalSpeed)RotationalSpeed.FromDeciradiansPerSecond(value);

        /// <inheritdoc cref="RotationalSpeed.FromDeciradiansPerSecond(double)"/>
        public static RotationalSpeed DeciradiansPerSecond(this decimal value) => (RotationalSpeed)RotationalSpeed.FromDeciradiansPerSecond(new Number<double, DoubleCalculator>(Decimal.ToDouble(value)));

        #endregion

        #region DegreePerMinute

        /// <inheritdoc cref="RotationalSpeed.FromDegreesPerMinute(double)"/>
        public static RotationalSpeed DegreesPerMinute(this int value) => (RotationalSpeed)RotationalSpeed.FromDegreesPerMinute(value);
	
        /// <inheritdoc cref="RotationalSpeed.FromDegreesPerMinute(double)"/>
        public static RotationalSpeed DegreesPerMinute(this long value) => (RotationalSpeed)RotationalSpeed.FromDegreesPerMinute(value);

        /// <inheritdoc cref="RotationalSpeed.FromDegreesPerMinute(double)"/>
        public static RotationalSpeed DegreesPerMinute(this double value) => (RotationalSpeed)RotationalSpeed.FromDegreesPerMinute(new Number<double, DoubleCalculator>(value));

        /// <inheritdoc cref="RotationalSpeed.FromDegreesPerMinute(double)"/>
        public static RotationalSpeed DegreesPerMinute(this float value) => (RotationalSpeed)RotationalSpeed.FromDegreesPerMinute(value);

        /// <inheritdoc cref="RotationalSpeed.FromDegreesPerMinute(double)"/>
        public static RotationalSpeed DegreesPerMinute(this decimal value) => (RotationalSpeed)RotationalSpeed.FromDegreesPerMinute(new Number<double, DoubleCalculator>(Decimal.ToDouble(value)));

        #endregion

        #region DegreePerSecond

        /// <inheritdoc cref="RotationalSpeed.FromDegreesPerSecond(double)"/>
        public static RotationalSpeed DegreesPerSecond(this int value) => (RotationalSpeed)RotationalSpeed.FromDegreesPerSecond(value);
	
        /// <inheritdoc cref="RotationalSpeed.FromDegreesPerSecond(double)"/>
        public static RotationalSpeed DegreesPerSecond(this long value) => (RotationalSpeed)RotationalSpeed.FromDegreesPerSecond(value);

        /// <inheritdoc cref="RotationalSpeed.FromDegreesPerSecond(double)"/>
        public static RotationalSpeed DegreesPerSecond(this double value) => (RotationalSpeed)RotationalSpeed.FromDegreesPerSecond(new Number<double, DoubleCalculator>(value));

        /// <inheritdoc cref="RotationalSpeed.FromDegreesPerSecond(double)"/>
        public static RotationalSpeed DegreesPerSecond(this float value) => (RotationalSpeed)RotationalSpeed.FromDegreesPerSecond(value);

        /// <inheritdoc cref="RotationalSpeed.FromDegreesPerSecond(double)"/>
        public static RotationalSpeed DegreesPerSecond(this decimal value) => (RotationalSpeed)RotationalSpeed.FromDegreesPerSecond(new Number<double, DoubleCalculator>(Decimal.ToDouble(value)));

        #endregion

        #region MicrodegreePerSecond

        /// <inheritdoc cref="RotationalSpeed.FromMicrodegreesPerSecond(double)"/>
        public static RotationalSpeed MicrodegreesPerSecond(this int value) => (RotationalSpeed)RotationalSpeed.FromMicrodegreesPerSecond(value);
	
        /// <inheritdoc cref="RotationalSpeed.FromMicrodegreesPerSecond(double)"/>
        public static RotationalSpeed MicrodegreesPerSecond(this long value) => (RotationalSpeed)RotationalSpeed.FromMicrodegreesPerSecond(value);

        /// <inheritdoc cref="RotationalSpeed.FromMicrodegreesPerSecond(double)"/>
        public static RotationalSpeed MicrodegreesPerSecond(this double value) => (RotationalSpeed)RotationalSpeed.FromMicrodegreesPerSecond(new Number<double, DoubleCalculator>(value));

        /// <inheritdoc cref="RotationalSpeed.FromMicrodegreesPerSecond(double)"/>
        public static RotationalSpeed MicrodegreesPerSecond(this float value) => (RotationalSpeed)RotationalSpeed.FromMicrodegreesPerSecond(value);

        /// <inheritdoc cref="RotationalSpeed.FromMicrodegreesPerSecond(double)"/>
        public static RotationalSpeed MicrodegreesPerSecond(this decimal value) => (RotationalSpeed)RotationalSpeed.FromMicrodegreesPerSecond(new Number<double, DoubleCalculator>(Decimal.ToDouble(value)));

        #endregion

        #region MicroradianPerSecond

        /// <inheritdoc cref="RotationalSpeed.FromMicroradiansPerSecond(double)"/>
        public static RotationalSpeed MicroradiansPerSecond(this int value) => (RotationalSpeed)RotationalSpeed.FromMicroradiansPerSecond(value);
	
        /// <inheritdoc cref="RotationalSpeed.FromMicroradiansPerSecond(double)"/>
        public static RotationalSpeed MicroradiansPerSecond(this long value) => (RotationalSpeed)RotationalSpeed.FromMicroradiansPerSecond(value);

        /// <inheritdoc cref="RotationalSpeed.FromMicroradiansPerSecond(double)"/>
        public static RotationalSpeed MicroradiansPerSecond(this double value) => (RotationalSpeed)RotationalSpeed.FromMicroradiansPerSecond(new Number<double, DoubleCalculator>(value));

        /// <inheritdoc cref="RotationalSpeed.FromMicroradiansPerSecond(double)"/>
        public static RotationalSpeed MicroradiansPerSecond(this float value) => (RotationalSpeed)RotationalSpeed.FromMicroradiansPerSecond(value);

        /// <inheritdoc cref="RotationalSpeed.FromMicroradiansPerSecond(double)"/>
        public static RotationalSpeed MicroradiansPerSecond(this decimal value) => (RotationalSpeed)RotationalSpeed.FromMicroradiansPerSecond(new Number<double, DoubleCalculator>(Decimal.ToDouble(value)));

        #endregion

        #region MillidegreePerSecond

        /// <inheritdoc cref="RotationalSpeed.FromMillidegreesPerSecond(double)"/>
        public static RotationalSpeed MillidegreesPerSecond(this int value) => (RotationalSpeed)RotationalSpeed.FromMillidegreesPerSecond(value);
	
        /// <inheritdoc cref="RotationalSpeed.FromMillidegreesPerSecond(double)"/>
        public static RotationalSpeed MillidegreesPerSecond(this long value) => (RotationalSpeed)RotationalSpeed.FromMillidegreesPerSecond(value);

        /// <inheritdoc cref="RotationalSpeed.FromMillidegreesPerSecond(double)"/>
        public static RotationalSpeed MillidegreesPerSecond(this double value) => (RotationalSpeed)RotationalSpeed.FromMillidegreesPerSecond(new Number<double, DoubleCalculator>(value));

        /// <inheritdoc cref="RotationalSpeed.FromMillidegreesPerSecond(double)"/>
        public static RotationalSpeed MillidegreesPerSecond(this float value) => (RotationalSpeed)RotationalSpeed.FromMillidegreesPerSecond(value);

        /// <inheritdoc cref="RotationalSpeed.FromMillidegreesPerSecond(double)"/>
        public static RotationalSpeed MillidegreesPerSecond(this decimal value) => (RotationalSpeed)RotationalSpeed.FromMillidegreesPerSecond(new Number<double, DoubleCalculator>(Decimal.ToDouble(value)));

        #endregion

        #region MilliradianPerSecond

        /// <inheritdoc cref="RotationalSpeed.FromMilliradiansPerSecond(double)"/>
        public static RotationalSpeed MilliradiansPerSecond(this int value) => (RotationalSpeed)RotationalSpeed.FromMilliradiansPerSecond(value);
	
        /// <inheritdoc cref="RotationalSpeed.FromMilliradiansPerSecond(double)"/>
        public static RotationalSpeed MilliradiansPerSecond(this long value) => (RotationalSpeed)RotationalSpeed.FromMilliradiansPerSecond(value);

        /// <inheritdoc cref="RotationalSpeed.FromMilliradiansPerSecond(double)"/>
        public static RotationalSpeed MilliradiansPerSecond(this double value) => (RotationalSpeed)RotationalSpeed.FromMilliradiansPerSecond(new Number<double, DoubleCalculator>(value));

        /// <inheritdoc cref="RotationalSpeed.FromMilliradiansPerSecond(double)"/>
        public static RotationalSpeed MilliradiansPerSecond(this float value) => (RotationalSpeed)RotationalSpeed.FromMilliradiansPerSecond(value);

        /// <inheritdoc cref="RotationalSpeed.FromMilliradiansPerSecond(double)"/>
        public static RotationalSpeed MilliradiansPerSecond(this decimal value) => (RotationalSpeed)RotationalSpeed.FromMilliradiansPerSecond(new Number<double, DoubleCalculator>(Decimal.ToDouble(value)));

        #endregion

        #region NanodegreePerSecond

        /// <inheritdoc cref="RotationalSpeed.FromNanodegreesPerSecond(double)"/>
        public static RotationalSpeed NanodegreesPerSecond(this int value) => (RotationalSpeed)RotationalSpeed.FromNanodegreesPerSecond(value);
	
        /// <inheritdoc cref="RotationalSpeed.FromNanodegreesPerSecond(double)"/>
        public static RotationalSpeed NanodegreesPerSecond(this long value) => (RotationalSpeed)RotationalSpeed.FromNanodegreesPerSecond(value);

        /// <inheritdoc cref="RotationalSpeed.FromNanodegreesPerSecond(double)"/>
        public static RotationalSpeed NanodegreesPerSecond(this double value) => (RotationalSpeed)RotationalSpeed.FromNanodegreesPerSecond(new Number<double, DoubleCalculator>(value));

        /// <inheritdoc cref="RotationalSpeed.FromNanodegreesPerSecond(double)"/>
        public static RotationalSpeed NanodegreesPerSecond(this float value) => (RotationalSpeed)RotationalSpeed.FromNanodegreesPerSecond(value);

        /// <inheritdoc cref="RotationalSpeed.FromNanodegreesPerSecond(double)"/>
        public static RotationalSpeed NanodegreesPerSecond(this decimal value) => (RotationalSpeed)RotationalSpeed.FromNanodegreesPerSecond(new Number<double, DoubleCalculator>(Decimal.ToDouble(value)));

        #endregion

        #region NanoradianPerSecond

        /// <inheritdoc cref="RotationalSpeed.FromNanoradiansPerSecond(double)"/>
        public static RotationalSpeed NanoradiansPerSecond(this int value) => (RotationalSpeed)RotationalSpeed.FromNanoradiansPerSecond(value);
	
        /// <inheritdoc cref="RotationalSpeed.FromNanoradiansPerSecond(double)"/>
        public static RotationalSpeed NanoradiansPerSecond(this long value) => (RotationalSpeed)RotationalSpeed.FromNanoradiansPerSecond(value);

        /// <inheritdoc cref="RotationalSpeed.FromNanoradiansPerSecond(double)"/>
        public static RotationalSpeed NanoradiansPerSecond(this double value) => (RotationalSpeed)RotationalSpeed.FromNanoradiansPerSecond(new Number<double, DoubleCalculator>(value));

        /// <inheritdoc cref="RotationalSpeed.FromNanoradiansPerSecond(double)"/>
        public static RotationalSpeed NanoradiansPerSecond(this float value) => (RotationalSpeed)RotationalSpeed.FromNanoradiansPerSecond(value);

        /// <inheritdoc cref="RotationalSpeed.FromNanoradiansPerSecond(double)"/>
        public static RotationalSpeed NanoradiansPerSecond(this decimal value) => (RotationalSpeed)RotationalSpeed.FromNanoradiansPerSecond(new Number<double, DoubleCalculator>(Decimal.ToDouble(value)));

        #endregion

        #region RadianPerSecond

        /// <inheritdoc cref="RotationalSpeed.FromRadiansPerSecond(double)"/>
        public static RotationalSpeed RadiansPerSecond(this int value) => (RotationalSpeed)RotationalSpeed.FromRadiansPerSecond(value);
	
        /// <inheritdoc cref="RotationalSpeed.FromRadiansPerSecond(double)"/>
        public static RotationalSpeed RadiansPerSecond(this long value) => (RotationalSpeed)RotationalSpeed.FromRadiansPerSecond(value);

        /// <inheritdoc cref="RotationalSpeed.FromRadiansPerSecond(double)"/>
        public static RotationalSpeed RadiansPerSecond(this double value) => (RotationalSpeed)RotationalSpeed.FromRadiansPerSecond(new Number<double, DoubleCalculator>(value));

        /// <inheritdoc cref="RotationalSpeed.FromRadiansPerSecond(double)"/>
        public static RotationalSpeed RadiansPerSecond(this float value) => (RotationalSpeed)RotationalSpeed.FromRadiansPerSecond(value);

        /// <inheritdoc cref="RotationalSpeed.FromRadiansPerSecond(double)"/>
        public static RotationalSpeed RadiansPerSecond(this decimal value) => (RotationalSpeed)RotationalSpeed.FromRadiansPerSecond(new Number<double, DoubleCalculator>(Decimal.ToDouble(value)));

        #endregion

        #region RevolutionPerMinute

        /// <inheritdoc cref="RotationalSpeed.FromRevolutionsPerMinute(double)"/>
        public static RotationalSpeed RevolutionsPerMinute(this int value) => (RotationalSpeed)RotationalSpeed.FromRevolutionsPerMinute(value);
	
        /// <inheritdoc cref="RotationalSpeed.FromRevolutionsPerMinute(double)"/>
        public static RotationalSpeed RevolutionsPerMinute(this long value) => (RotationalSpeed)RotationalSpeed.FromRevolutionsPerMinute(value);

        /// <inheritdoc cref="RotationalSpeed.FromRevolutionsPerMinute(double)"/>
        public static RotationalSpeed RevolutionsPerMinute(this double value) => (RotationalSpeed)RotationalSpeed.FromRevolutionsPerMinute(new Number<double, DoubleCalculator>(value));

        /// <inheritdoc cref="RotationalSpeed.FromRevolutionsPerMinute(double)"/>
        public static RotationalSpeed RevolutionsPerMinute(this float value) => (RotationalSpeed)RotationalSpeed.FromRevolutionsPerMinute(value);

        /// <inheritdoc cref="RotationalSpeed.FromRevolutionsPerMinute(double)"/>
        public static RotationalSpeed RevolutionsPerMinute(this decimal value) => (RotationalSpeed)RotationalSpeed.FromRevolutionsPerMinute(new Number<double, DoubleCalculator>(Decimal.ToDouble(value)));

        #endregion

        #region RevolutionPerSecond

        /// <inheritdoc cref="RotationalSpeed.FromRevolutionsPerSecond(double)"/>
        public static RotationalSpeed RevolutionsPerSecond(this int value) => (RotationalSpeed)RotationalSpeed.FromRevolutionsPerSecond(value);
	
        /// <inheritdoc cref="RotationalSpeed.FromRevolutionsPerSecond(double)"/>
        public static RotationalSpeed RevolutionsPerSecond(this long value) => (RotationalSpeed)RotationalSpeed.FromRevolutionsPerSecond(value);

        /// <inheritdoc cref="RotationalSpeed.FromRevolutionsPerSecond(double)"/>
        public static RotationalSpeed RevolutionsPerSecond(this double value) => (RotationalSpeed)RotationalSpeed.FromRevolutionsPerSecond(new Number<double, DoubleCalculator>(value));

        /// <inheritdoc cref="RotationalSpeed.FromRevolutionsPerSecond(double)"/>
        public static RotationalSpeed RevolutionsPerSecond(this float value) => (RotationalSpeed)RotationalSpeed.FromRevolutionsPerSecond(value);

        /// <inheritdoc cref="RotationalSpeed.FromRevolutionsPerSecond(double)"/>
        public static RotationalSpeed RevolutionsPerSecond(this decimal value) => (RotationalSpeed)RotationalSpeed.FromRevolutionsPerSecond(new Number<double, DoubleCalculator>(Decimal.ToDouble(value)));

        #endregion

    }
}
#endif
