//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyUnit.extra.cs files to add code to generated quantities.
//     Add Extensions\MyUnitExtensions.cs to decorate quantities with new behavior.
//     Add UnitDefinitions\MyUnit.json and run GeneratUnits.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Copyright (c) 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com).
// https://github.com/angularsen/UnitsNet
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

using System;
using UnitsNet.InternalHelpers.Calculators;

// Windows Runtime Component does not support extension methods and method overloads: https://msdn.microsoft.com/en-us/library/br230301.aspx
#if !WINDOWS_UWP
namespace UnitsNet.Extensions.NumberToEntropy
{
    public static class NumberToEntropyExtensions
    {
        #region CaloriePerKelvin

        /// <inheritdoc cref="Entropy.FromCaloriesPerKelvin(double)"/>
        public static Entropy CaloriesPerKelvin(this int value) => (Entropy)Entropy.FromCaloriesPerKelvin(value);
	
        /// <inheritdoc cref="Entropy.FromCaloriesPerKelvin(double)"/>
        public static Entropy CaloriesPerKelvin(this long value) => (Entropy)Entropy.FromCaloriesPerKelvin(value);

        /// <inheritdoc cref="Entropy.FromCaloriesPerKelvin(double)"/>
        public static Entropy CaloriesPerKelvin(this double value) => (Entropy)Entropy.FromCaloriesPerKelvin(new Number<double, DoubleCalculator>(value));

        /// <inheritdoc cref="Entropy.FromCaloriesPerKelvin(double)"/>
        public static Entropy CaloriesPerKelvin(this float value) => (Entropy)Entropy.FromCaloriesPerKelvin(value);

        /// <inheritdoc cref="Entropy.FromCaloriesPerKelvin(double)"/>
        public static Entropy CaloriesPerKelvin(this decimal value) => (Entropy)Entropy.FromCaloriesPerKelvin(new Number<double, DoubleCalculator>(Decimal.ToDouble(value)));

        #endregion

        #region JoulePerDegreeCelsius

        /// <inheritdoc cref="Entropy.FromJoulesPerDegreeCelsius(double)"/>
        public static Entropy JoulesPerDegreeCelsius(this int value) => (Entropy)Entropy.FromJoulesPerDegreeCelsius(value);
	
        /// <inheritdoc cref="Entropy.FromJoulesPerDegreeCelsius(double)"/>
        public static Entropy JoulesPerDegreeCelsius(this long value) => (Entropy)Entropy.FromJoulesPerDegreeCelsius(value);

        /// <inheritdoc cref="Entropy.FromJoulesPerDegreeCelsius(double)"/>
        public static Entropy JoulesPerDegreeCelsius(this double value) => (Entropy)Entropy.FromJoulesPerDegreeCelsius(new Number<double, DoubleCalculator>(value));

        /// <inheritdoc cref="Entropy.FromJoulesPerDegreeCelsius(double)"/>
        public static Entropy JoulesPerDegreeCelsius(this float value) => (Entropy)Entropy.FromJoulesPerDegreeCelsius(value);

        /// <inheritdoc cref="Entropy.FromJoulesPerDegreeCelsius(double)"/>
        public static Entropy JoulesPerDegreeCelsius(this decimal value) => (Entropy)Entropy.FromJoulesPerDegreeCelsius(new Number<double, DoubleCalculator>(Decimal.ToDouble(value)));

        #endregion

        #region JoulePerKelvin

        /// <inheritdoc cref="Entropy.FromJoulesPerKelvin(double)"/>
        public static Entropy JoulesPerKelvin(this int value) => (Entropy)Entropy.FromJoulesPerKelvin(value);
	
        /// <inheritdoc cref="Entropy.FromJoulesPerKelvin(double)"/>
        public static Entropy JoulesPerKelvin(this long value) => (Entropy)Entropy.FromJoulesPerKelvin(value);

        /// <inheritdoc cref="Entropy.FromJoulesPerKelvin(double)"/>
        public static Entropy JoulesPerKelvin(this double value) => (Entropy)Entropy.FromJoulesPerKelvin(new Number<double, DoubleCalculator>(value));

        /// <inheritdoc cref="Entropy.FromJoulesPerKelvin(double)"/>
        public static Entropy JoulesPerKelvin(this float value) => (Entropy)Entropy.FromJoulesPerKelvin(value);

        /// <inheritdoc cref="Entropy.FromJoulesPerKelvin(double)"/>
        public static Entropy JoulesPerKelvin(this decimal value) => (Entropy)Entropy.FromJoulesPerKelvin(new Number<double, DoubleCalculator>(Decimal.ToDouble(value)));

        #endregion

        #region KilocaloriePerKelvin

        /// <inheritdoc cref="Entropy.FromKilocaloriesPerKelvin(double)"/>
        public static Entropy KilocaloriesPerKelvin(this int value) => (Entropy)Entropy.FromKilocaloriesPerKelvin(value);
	
        /// <inheritdoc cref="Entropy.FromKilocaloriesPerKelvin(double)"/>
        public static Entropy KilocaloriesPerKelvin(this long value) => (Entropy)Entropy.FromKilocaloriesPerKelvin(value);

        /// <inheritdoc cref="Entropy.FromKilocaloriesPerKelvin(double)"/>
        public static Entropy KilocaloriesPerKelvin(this double value) => (Entropy)Entropy.FromKilocaloriesPerKelvin(new Number<double, DoubleCalculator>(value));

        /// <inheritdoc cref="Entropy.FromKilocaloriesPerKelvin(double)"/>
        public static Entropy KilocaloriesPerKelvin(this float value) => (Entropy)Entropy.FromKilocaloriesPerKelvin(value);

        /// <inheritdoc cref="Entropy.FromKilocaloriesPerKelvin(double)"/>
        public static Entropy KilocaloriesPerKelvin(this decimal value) => (Entropy)Entropy.FromKilocaloriesPerKelvin(new Number<double, DoubleCalculator>(Decimal.ToDouble(value)));

        #endregion

        #region KilojoulePerDegreeCelsius

        /// <inheritdoc cref="Entropy.FromKilojoulesPerDegreeCelsius(double)"/>
        public static Entropy KilojoulesPerDegreeCelsius(this int value) => (Entropy)Entropy.FromKilojoulesPerDegreeCelsius(value);
	
        /// <inheritdoc cref="Entropy.FromKilojoulesPerDegreeCelsius(double)"/>
        public static Entropy KilojoulesPerDegreeCelsius(this long value) => (Entropy)Entropy.FromKilojoulesPerDegreeCelsius(value);

        /// <inheritdoc cref="Entropy.FromKilojoulesPerDegreeCelsius(double)"/>
        public static Entropy KilojoulesPerDegreeCelsius(this double value) => (Entropy)Entropy.FromKilojoulesPerDegreeCelsius(new Number<double, DoubleCalculator>(value));

        /// <inheritdoc cref="Entropy.FromKilojoulesPerDegreeCelsius(double)"/>
        public static Entropy KilojoulesPerDegreeCelsius(this float value) => (Entropy)Entropy.FromKilojoulesPerDegreeCelsius(value);

        /// <inheritdoc cref="Entropy.FromKilojoulesPerDegreeCelsius(double)"/>
        public static Entropy KilojoulesPerDegreeCelsius(this decimal value) => (Entropy)Entropy.FromKilojoulesPerDegreeCelsius(new Number<double, DoubleCalculator>(Decimal.ToDouble(value)));

        #endregion

        #region KilojoulePerKelvin

        /// <inheritdoc cref="Entropy.FromKilojoulesPerKelvin(double)"/>
        public static Entropy KilojoulesPerKelvin(this int value) => (Entropy)Entropy.FromKilojoulesPerKelvin(value);
	
        /// <inheritdoc cref="Entropy.FromKilojoulesPerKelvin(double)"/>
        public static Entropy KilojoulesPerKelvin(this long value) => (Entropy)Entropy.FromKilojoulesPerKelvin(value);

        /// <inheritdoc cref="Entropy.FromKilojoulesPerKelvin(double)"/>
        public static Entropy KilojoulesPerKelvin(this double value) => (Entropy)Entropy.FromKilojoulesPerKelvin(new Number<double, DoubleCalculator>(value));

        /// <inheritdoc cref="Entropy.FromKilojoulesPerKelvin(double)"/>
        public static Entropy KilojoulesPerKelvin(this float value) => (Entropy)Entropy.FromKilojoulesPerKelvin(value);

        /// <inheritdoc cref="Entropy.FromKilojoulesPerKelvin(double)"/>
        public static Entropy KilojoulesPerKelvin(this decimal value) => (Entropy)Entropy.FromKilojoulesPerKelvin(new Number<double, DoubleCalculator>(Decimal.ToDouble(value)));

        #endregion

        #region MegajoulePerKelvin

        /// <inheritdoc cref="Entropy.FromMegajoulesPerKelvin(double)"/>
        public static Entropy MegajoulesPerKelvin(this int value) => (Entropy)Entropy.FromMegajoulesPerKelvin(value);
	
        /// <inheritdoc cref="Entropy.FromMegajoulesPerKelvin(double)"/>
        public static Entropy MegajoulesPerKelvin(this long value) => (Entropy)Entropy.FromMegajoulesPerKelvin(value);

        /// <inheritdoc cref="Entropy.FromMegajoulesPerKelvin(double)"/>
        public static Entropy MegajoulesPerKelvin(this double value) => (Entropy)Entropy.FromMegajoulesPerKelvin(new Number<double, DoubleCalculator>(value));

        /// <inheritdoc cref="Entropy.FromMegajoulesPerKelvin(double)"/>
        public static Entropy MegajoulesPerKelvin(this float value) => (Entropy)Entropy.FromMegajoulesPerKelvin(value);

        /// <inheritdoc cref="Entropy.FromMegajoulesPerKelvin(double)"/>
        public static Entropy MegajoulesPerKelvin(this decimal value) => (Entropy)Entropy.FromMegajoulesPerKelvin(new Number<double, DoubleCalculator>(Decimal.ToDouble(value)));

        #endregion

    }
}
#endif
