//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyUnit.extra.cs files to add code to generated quantities.
//     Add Extensions\MyUnitExtensions.cs to decorate quantities with new behavior.
//     Add UnitDefinitions\MyUnit.json and run GeneratUnits.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Copyright (c) 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com).
// https://github.com/angularsen/UnitsNet
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

using System;
using UnitsNet.InternalHelpers.Calculators;

// Windows Runtime Component does not support extension methods and method overloads: https://msdn.microsoft.com/en-us/library/br230301.aspx
#if !WINDOWS_UWP
namespace UnitsNet.Extensions.NumberToPressureChangeRate
{
    public static class NumberToPressureChangeRateExtensions
    {
        #region AtmospherePerSecond

        /// <inheritdoc cref="PressureChangeRate.FromAtmospheresPerSecond(double)"/>
        public static PressureChangeRate AtmospheresPerSecond(this int value) => (PressureChangeRate)PressureChangeRate.FromAtmospheresPerSecond(value);
	
        /// <inheritdoc cref="PressureChangeRate.FromAtmospheresPerSecond(double)"/>
        public static PressureChangeRate AtmospheresPerSecond(this long value) => (PressureChangeRate)PressureChangeRate.FromAtmospheresPerSecond(value);

        /// <inheritdoc cref="PressureChangeRate.FromAtmospheresPerSecond(double)"/>
        public static PressureChangeRate AtmospheresPerSecond(this double value) => (PressureChangeRate)PressureChangeRate.FromAtmospheresPerSecond(new Number<double, DoubleCalculator>(value));

        /// <inheritdoc cref="PressureChangeRate.FromAtmospheresPerSecond(double)"/>
        public static PressureChangeRate AtmospheresPerSecond(this float value) => (PressureChangeRate)PressureChangeRate.FromAtmospheresPerSecond(value);

        /// <inheritdoc cref="PressureChangeRate.FromAtmospheresPerSecond(double)"/>
        public static PressureChangeRate AtmospheresPerSecond(this decimal value) => (PressureChangeRate)PressureChangeRate.FromAtmospheresPerSecond(new Number<double, DoubleCalculator>(Decimal.ToDouble(value)));

        #endregion

        #region KilopascalPerSecond

        /// <inheritdoc cref="PressureChangeRate.FromKilopascalsPerSecond(double)"/>
        public static PressureChangeRate KilopascalsPerSecond(this int value) => (PressureChangeRate)PressureChangeRate.FromKilopascalsPerSecond(value);
	
        /// <inheritdoc cref="PressureChangeRate.FromKilopascalsPerSecond(double)"/>
        public static PressureChangeRate KilopascalsPerSecond(this long value) => (PressureChangeRate)PressureChangeRate.FromKilopascalsPerSecond(value);

        /// <inheritdoc cref="PressureChangeRate.FromKilopascalsPerSecond(double)"/>
        public static PressureChangeRate KilopascalsPerSecond(this double value) => (PressureChangeRate)PressureChangeRate.FromKilopascalsPerSecond(new Number<double, DoubleCalculator>(value));

        /// <inheritdoc cref="PressureChangeRate.FromKilopascalsPerSecond(double)"/>
        public static PressureChangeRate KilopascalsPerSecond(this float value) => (PressureChangeRate)PressureChangeRate.FromKilopascalsPerSecond(value);

        /// <inheritdoc cref="PressureChangeRate.FromKilopascalsPerSecond(double)"/>
        public static PressureChangeRate KilopascalsPerSecond(this decimal value) => (PressureChangeRate)PressureChangeRate.FromKilopascalsPerSecond(new Number<double, DoubleCalculator>(Decimal.ToDouble(value)));

        #endregion

        #region MegapascalPerSecond

        /// <inheritdoc cref="PressureChangeRate.FromMegapascalsPerSecond(double)"/>
        public static PressureChangeRate MegapascalsPerSecond(this int value) => (PressureChangeRate)PressureChangeRate.FromMegapascalsPerSecond(value);
	
        /// <inheritdoc cref="PressureChangeRate.FromMegapascalsPerSecond(double)"/>
        public static PressureChangeRate MegapascalsPerSecond(this long value) => (PressureChangeRate)PressureChangeRate.FromMegapascalsPerSecond(value);

        /// <inheritdoc cref="PressureChangeRate.FromMegapascalsPerSecond(double)"/>
        public static PressureChangeRate MegapascalsPerSecond(this double value) => (PressureChangeRate)PressureChangeRate.FromMegapascalsPerSecond(new Number<double, DoubleCalculator>(value));

        /// <inheritdoc cref="PressureChangeRate.FromMegapascalsPerSecond(double)"/>
        public static PressureChangeRate MegapascalsPerSecond(this float value) => (PressureChangeRate)PressureChangeRate.FromMegapascalsPerSecond(value);

        /// <inheritdoc cref="PressureChangeRate.FromMegapascalsPerSecond(double)"/>
        public static PressureChangeRate MegapascalsPerSecond(this decimal value) => (PressureChangeRate)PressureChangeRate.FromMegapascalsPerSecond(new Number<double, DoubleCalculator>(Decimal.ToDouble(value)));

        #endregion

        #region PascalPerSecond

        /// <inheritdoc cref="PressureChangeRate.FromPascalsPerSecond(double)"/>
        public static PressureChangeRate PascalsPerSecond(this int value) => (PressureChangeRate)PressureChangeRate.FromPascalsPerSecond(value);
	
        /// <inheritdoc cref="PressureChangeRate.FromPascalsPerSecond(double)"/>
        public static PressureChangeRate PascalsPerSecond(this long value) => (PressureChangeRate)PressureChangeRate.FromPascalsPerSecond(value);

        /// <inheritdoc cref="PressureChangeRate.FromPascalsPerSecond(double)"/>
        public static PressureChangeRate PascalsPerSecond(this double value) => (PressureChangeRate)PressureChangeRate.FromPascalsPerSecond(new Number<double, DoubleCalculator>(value));

        /// <inheritdoc cref="PressureChangeRate.FromPascalsPerSecond(double)"/>
        public static PressureChangeRate PascalsPerSecond(this float value) => (PressureChangeRate)PressureChangeRate.FromPascalsPerSecond(value);

        /// <inheritdoc cref="PressureChangeRate.FromPascalsPerSecond(double)"/>
        public static PressureChangeRate PascalsPerSecond(this decimal value) => (PressureChangeRate)PressureChangeRate.FromPascalsPerSecond(new Number<double, DoubleCalculator>(Decimal.ToDouble(value)));

        #endregion

    }
}
#endif
