//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyUnit.extra.cs files to add code to generated quantities.
//     Add Extensions\MyUnitExtensions.cs to decorate quantities with new behavior.
//     Add UnitDefinitions\MyUnit.json and run GeneratUnits.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Copyright (c) 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com).
// https://github.com/angularsen/UnitsNet
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text.RegularExpressions;
using System.Linq;
using JetBrains.Annotations;
using UnitsNet.Units;

// Windows Runtime Component does not support CultureInfo type, so use culture name string instead for public methods: https://msdn.microsoft.com/en-us/library/br230301.aspx
#if WINDOWS_UWP
using Culture = System.String;
#else
using Culture = System.IFormatProvider;
#endif

// ReSharper disable once CheckNamespace
namespace UnitsNet
{
    using UnitsNet.InternalHelpers.Calculators;

    /// <summary>
    ///     Acceleration, in physics, is the rate at which the velocity of an object changes over time. An object's acceleration is the net result of any and all forces acting on the object, as described by Newton's Second Law. The SI unit for acceleration is the Meter per second squared (m/s²). Accelerations are vector quantities (they have magnitude and direction) and add according to the parallelogram law. As a vector, the calculated net force is equal to the product of the object's mass (a scalar quantity) and the acceleration.
    /// </summary>
    // ReSharper disable once PartialTypeWithSinglePart

    // Windows Runtime Component has constraints on public types: https://msdn.microsoft.com/en-us/library/br230301.aspx#Declaring types in Windows Runtime Components
    // Public structures can't have any members other than public fields, and those fields must be value types or strings.
    // Public classes must be sealed (NotInheritable in Visual Basic). If your programming model requires polymorphism, you can create a public interface and implement that interface on the classes that must be polymorphic.
	public partial class Acceleration : UnitsNet.Generic.Acceleration<double, UnitsNet.InternalHelpers.Calculators.DoubleCalculator>
    {
        public Acceleration(double meterpersecondsquared) : base(meterpersecondsquared)
        {
        }

        public static implicit operator Acceleration(Number<double, DoubleCalculator> d)
        {
            return new Acceleration(d);
        }
    }

	namespace Generic
	{
#if WINDOWS_UWP
		public sealed partial class Acceleration
#else
		public partial class Acceleration <T, C> : IComparable, IComparable<Acceleration<T, C>>
			where T : struct
			where C : InternalHelpers.Calculators.INumberCalculator<T>, new()
#endif
		{
			/// <summary>
			///     Base unit of Acceleration.
			/// </summary>
			private readonly Number<T, C> _meterPerSecondSquared;

			public Acceleration() : this(new Number<T,C>())
			{
			}

			public Acceleration(T meterpersecondsquared)
			{
				_meterPerSecondSquared = (meterpersecondsquared);
			}

			public Acceleration(Number<T, C> meterpersecondsquared)
			{
				_meterPerSecondSquared = (meterpersecondsquared);
			}

			#region Properties

			/// <summary>
			///     The <see cref="QuantityType" /> of this quantity.
			/// </summary>
			public static QuantityType QuantityType => QuantityType.Acceleration;

			/// <summary>
			///     The base unit representation of this quantity for the numeric value stored internally. All conversions go via this value.
			/// </summary>
			public static AccelerationUnit BaseUnit
			{
				get { return AccelerationUnit.MeterPerSecondSquared; }
			}

			/// <summary>
			///     All units of measurement for the Acceleration quantity.
			/// </summary>
			public static AccelerationUnit[] Units { get; } = Enum.GetValues(typeof(AccelerationUnit)).Cast<AccelerationUnit>().ToArray();

			/// <summary>
			///     Get Acceleration in CentimeterPerSecondSquared.
			/// </summary>
			public Number<T, C> CentimeterPerSecondSquared
			{
				get { return (_meterPerSecondSquared) / 1e-2d; }
			}

			/// <summary>
			///     Get Acceleration in DecimeterPerSecondSquared.
			/// </summary>
			public Number<T, C> DecimeterPerSecondSquared
			{
				get { return (_meterPerSecondSquared) / 1e-1d; }
			}

			/// <summary>
			///     Get Acceleration in FeetPerSecondSquared.
			/// </summary>
			public Number<T, C> FeetPerSecondSquared
			{
				get { return _meterPerSecondSquared/0.304800; }
			}

			/// <summary>
			///     Get Acceleration in InchesPerSecondSquared.
			/// </summary>
			public Number<T, C> InchesPerSecondSquared
			{
				get { return _meterPerSecondSquared/0.0254; }
			}

			/// <summary>
			///     Get Acceleration in KilometerPerSecondSquared.
			/// </summary>
			public Number<T, C> KilometerPerSecondSquared
			{
				get { return (_meterPerSecondSquared) / 1e3d; }
			}

			/// <summary>
			///     Get Acceleration in MeterPerSecondSquared.
			/// </summary>
			public Number<T, C> MeterPerSecondSquared
			{
				get { return _meterPerSecondSquared; }
			}

			/// <summary>
			///     Get Acceleration in MicrometerPerSecondSquared.
			/// </summary>
			public Number<T, C> MicrometerPerSecondSquared
			{
				get { return (_meterPerSecondSquared) / 1e-6d; }
			}

			/// <summary>
			///     Get Acceleration in MillimeterPerSecondSquared.
			/// </summary>
			public Number<T, C> MillimeterPerSecondSquared
			{
				get { return (_meterPerSecondSquared) / 1e-3d; }
			}

			/// <summary>
			///     Get Acceleration in NanometerPerSecondSquared.
			/// </summary>
			public Number<T, C> NanometerPerSecondSquared
			{
				get { return (_meterPerSecondSquared) / 1e-9d; }
			}

			/// <summary>
			///     Get Acceleration in StandardGravity.
			/// </summary>
			public Number<T, C> StandardGravity
			{
				get { return _meterPerSecondSquared/9.80665; }
			}

			#endregion

			#region Static

			public static Acceleration<T, C> Zero
			{
				get { return new Acceleration<T, C>(); }
			}

			/// <summary>
			///     Get Acceleration from CentimeterPerSecondSquared.
			/// </summary>
#if WINDOWS_UWP
			[Windows.Foundation.Metadata.DefaultOverload]
			public static Acceleration<T, C> FromCentimeterPerSecondSquared(Number<T, C> centimeterpersecondsquared)
			{
				Number<T,C> value = (Number<T,C>) centimeterpersecondsquared;
				return new Acceleration<T, C>((value) * 1e-2d);
			}
#else
			public static Acceleration<T, C> FromCentimeterPerSecondSquared(Number<T, C> centimeterpersecondsquared)
			{
				Number<T,C> value = (Number<T,C>) centimeterpersecondsquared;
				return new Acceleration<T, C>(new Number<T,C>((value) * 1e-2d));
			}
#endif

			/// <summary>
			///     Get Acceleration from DecimeterPerSecondSquared.
			/// </summary>
#if WINDOWS_UWP
			[Windows.Foundation.Metadata.DefaultOverload]
			public static Acceleration<T, C> FromDecimeterPerSecondSquared(Number<T, C> decimeterpersecondsquared)
			{
				Number<T,C> value = (Number<T,C>) decimeterpersecondsquared;
				return new Acceleration<T, C>((value) * 1e-1d);
			}
#else
			public static Acceleration<T, C> FromDecimeterPerSecondSquared(Number<T, C> decimeterpersecondsquared)
			{
				Number<T,C> value = (Number<T,C>) decimeterpersecondsquared;
				return new Acceleration<T, C>(new Number<T,C>((value) * 1e-1d));
			}
#endif

			/// <summary>
			///     Get Acceleration from FeetPerSecondSquared.
			/// </summary>
#if WINDOWS_UWP
			[Windows.Foundation.Metadata.DefaultOverload]
			public static Acceleration<T, C> FromFeetPerSecondSquared(Number<T, C> feetpersecondsquared)
			{
				Number<T,C> value = (Number<T,C>) feetpersecondsquared;
				return new Acceleration<T, C>(value*0.304800);
			}
#else
			public static Acceleration<T, C> FromFeetPerSecondSquared(Number<T, C> feetpersecondsquared)
			{
				Number<T,C> value = (Number<T,C>) feetpersecondsquared;
				return new Acceleration<T, C>(new Number<T,C>(value*0.304800));
			}
#endif

			/// <summary>
			///     Get Acceleration from InchesPerSecondSquared.
			/// </summary>
#if WINDOWS_UWP
			[Windows.Foundation.Metadata.DefaultOverload]
			public static Acceleration<T, C> FromInchesPerSecondSquared(Number<T, C> inchespersecondsquared)
			{
				Number<T,C> value = (Number<T,C>) inchespersecondsquared;
				return new Acceleration<T, C>(value*0.0254);
			}
#else
			public static Acceleration<T, C> FromInchesPerSecondSquared(Number<T, C> inchespersecondsquared)
			{
				Number<T,C> value = (Number<T,C>) inchespersecondsquared;
				return new Acceleration<T, C>(new Number<T,C>(value*0.0254));
			}
#endif

			/// <summary>
			///     Get Acceleration from KilometerPerSecondSquared.
			/// </summary>
#if WINDOWS_UWP
			[Windows.Foundation.Metadata.DefaultOverload]
			public static Acceleration<T, C> FromKilometerPerSecondSquared(Number<T, C> kilometerpersecondsquared)
			{
				Number<T,C> value = (Number<T,C>) kilometerpersecondsquared;
				return new Acceleration<T, C>((value) * 1e3d);
			}
#else
			public static Acceleration<T, C> FromKilometerPerSecondSquared(Number<T, C> kilometerpersecondsquared)
			{
				Number<T,C> value = (Number<T,C>) kilometerpersecondsquared;
				return new Acceleration<T, C>(new Number<T,C>((value) * 1e3d));
			}
#endif

			/// <summary>
			///     Get Acceleration from MeterPerSecondSquared.
			/// </summary>
#if WINDOWS_UWP
			[Windows.Foundation.Metadata.DefaultOverload]
			public static Acceleration<T, C> FromMeterPerSecondSquared(Number<T, C> meterpersecondsquared)
			{
				Number<T,C> value = (Number<T,C>) meterpersecondsquared;
				return new Acceleration<T, C>(value);
			}
#else
			public static Acceleration<T, C> FromMeterPerSecondSquared(Number<T, C> meterpersecondsquared)
			{
				Number<T,C> value = (Number<T,C>) meterpersecondsquared;
				return new Acceleration<T, C>(new Number<T,C>(value));
			}
#endif

			/// <summary>
			///     Get Acceleration from MicrometerPerSecondSquared.
			/// </summary>
#if WINDOWS_UWP
			[Windows.Foundation.Metadata.DefaultOverload]
			public static Acceleration<T, C> FromMicrometerPerSecondSquared(Number<T, C> micrometerpersecondsquared)
			{
				Number<T,C> value = (Number<T,C>) micrometerpersecondsquared;
				return new Acceleration<T, C>((value) * 1e-6d);
			}
#else
			public static Acceleration<T, C> FromMicrometerPerSecondSquared(Number<T, C> micrometerpersecondsquared)
			{
				Number<T,C> value = (Number<T,C>) micrometerpersecondsquared;
				return new Acceleration<T, C>(new Number<T,C>((value) * 1e-6d));
			}
#endif

			/// <summary>
			///     Get Acceleration from MillimeterPerSecondSquared.
			/// </summary>
#if WINDOWS_UWP
			[Windows.Foundation.Metadata.DefaultOverload]
			public static Acceleration<T, C> FromMillimeterPerSecondSquared(Number<T, C> millimeterpersecondsquared)
			{
				Number<T,C> value = (Number<T,C>) millimeterpersecondsquared;
				return new Acceleration<T, C>((value) * 1e-3d);
			}
#else
			public static Acceleration<T, C> FromMillimeterPerSecondSquared(Number<T, C> millimeterpersecondsquared)
			{
				Number<T,C> value = (Number<T,C>) millimeterpersecondsquared;
				return new Acceleration<T, C>(new Number<T,C>((value) * 1e-3d));
			}
#endif

			/// <summary>
			///     Get Acceleration from NanometerPerSecondSquared.
			/// </summary>
#if WINDOWS_UWP
			[Windows.Foundation.Metadata.DefaultOverload]
			public static Acceleration<T, C> FromNanometerPerSecondSquared(Number<T, C> nanometerpersecondsquared)
			{
				Number<T,C> value = (Number<T,C>) nanometerpersecondsquared;
				return new Acceleration<T, C>((value) * 1e-9d);
			}
#else
			public static Acceleration<T, C> FromNanometerPerSecondSquared(Number<T, C> nanometerpersecondsquared)
			{
				Number<T,C> value = (Number<T,C>) nanometerpersecondsquared;
				return new Acceleration<T, C>(new Number<T,C>((value) * 1e-9d));
			}
#endif

			/// <summary>
			///     Get Acceleration from StandardGravity.
			/// </summary>
#if WINDOWS_UWP
			[Windows.Foundation.Metadata.DefaultOverload]
			public static Acceleration<T, C> FromStandardGravity(Number<T, C> standardgravity)
			{
				Number<T,C> value = (Number<T,C>) standardgravity;
				return new Acceleration<T, C>(value*9.80665);
			}
#else
			public static Acceleration<T, C> FromStandardGravity(Number<T, C> standardgravity)
			{
				Number<T,C> value = (Number<T,C>) standardgravity;
				return new Acceleration<T, C>(new Number<T,C>(value*9.80665));
			}
#endif



			/// <summary>
			///     Dynamically convert from value and unit enum <see cref="AccelerationUnit" /> to <see cref="Acceleration" />.
			/// </summary>
			/// <param name="value">Value to convert from.</param>
			/// <param name="fromUnit">Unit to convert from.</param>
			/// <returns>Acceleration unit value.</returns>
#if WINDOWS_UWP
			// Fix name conflict with parameter "value"
			[return: System.Runtime.InteropServices.WindowsRuntime.ReturnValueName("returnValue")]
			public static Acceleration<T, C> From(double value, AccelerationUnit fromUnit)
#else
			public static Acceleration<T, C> From(Number<T, C> value, AccelerationUnit fromUnit)
#endif
			{
				switch (fromUnit)
				{
					case AccelerationUnit.CentimeterPerSecondSquared:
						return FromCentimeterPerSecondSquared(value);
					case AccelerationUnit.DecimeterPerSecondSquared:
						return FromDecimeterPerSecondSquared(value);
					case AccelerationUnit.FootPerSecondSquared:
						return FromFeetPerSecondSquared(value);
					case AccelerationUnit.InchPerSecondSquared:
						return FromInchesPerSecondSquared(value);
					case AccelerationUnit.KilometerPerSecondSquared:
						return FromKilometerPerSecondSquared(value);
					case AccelerationUnit.MeterPerSecondSquared:
						return FromMeterPerSecondSquared(value);
					case AccelerationUnit.MicrometerPerSecondSquared:
						return FromMicrometerPerSecondSquared(value);
					case AccelerationUnit.MillimeterPerSecondSquared:
						return FromMillimeterPerSecondSquared(value);
					case AccelerationUnit.NanometerPerSecondSquared:
						return FromNanometerPerSecondSquared(value);
					case AccelerationUnit.StandardGravity:
						return FromStandardGravity(value);

					default:
						throw new NotImplementedException("fromUnit: " + fromUnit);
				}
			}

			/// <summary>
			///     Get unit abbreviation string.
			/// </summary>
			/// <param name="unit">Unit to get abbreviation for.</param>
			/// <returns>Unit abbreviation string.</returns>
			[UsedImplicitly]
			public static string GetAbbreviation(AccelerationUnit unit)
			{
				return GetAbbreviation(unit, null);
			}

			/// <summary>
			///     Get unit abbreviation string.
			/// </summary>
			/// <param name="unit">Unit to get abbreviation for.</param>
			/// <param name="culture">Culture to use for localization. Defaults to Thread.CurrentUICulture.</param>
			/// <returns>Unit abbreviation string.</returns>
			[UsedImplicitly]
			public static string GetAbbreviation(AccelerationUnit unit, [CanBeNull] Culture culture)
			{
				return UnitSystem.GetCached(culture).GetDefaultAbbreviation(unit);
			}

			#endregion

			#region Arithmetic Operators

			// Windows Runtime Component does not allow operator overloads: https://msdn.microsoft.com/en-us/library/br230301.aspx
#if !WINDOWS_UWP
			public static Acceleration<T, C> operator -(Acceleration<T, C> right)
			{
				return new Acceleration<T, C>(-right._meterPerSecondSquared);
			}

			public static Acceleration<T, C> operator +(Acceleration<T, C> left, Acceleration<T, C> right)
			{
				return new Acceleration<T, C>(left._meterPerSecondSquared + right._meterPerSecondSquared);
			}

			public static Acceleration<T, C> operator -(Acceleration<T, C> left, Acceleration<T, C> right)
			{
				return new Acceleration<T, C>(left._meterPerSecondSquared - right._meterPerSecondSquared);
			}

			public static Acceleration<T, C> operator *(Number<T, C> left, Acceleration<T, C> right)
			{
				return new Acceleration<T, C>(left*right._meterPerSecondSquared);
			}

			public static Acceleration<T, C> operator *(Acceleration<T, C> left, double right)
			{
				return new Acceleration<T, C>(left._meterPerSecondSquared*right);
			}

			public static Acceleration<T, C> operator /(Acceleration<T, C> left, double right)
			{
				return new Acceleration<T, C>(left._meterPerSecondSquared/right);
			}

			public static double operator /(Acceleration<T, C> left, Acceleration<T, C> right)
			{
				return Convert.ToDouble(left._meterPerSecondSquared/right._meterPerSecondSquared);
			}
#endif

			#endregion

			#region Equality / IComparable

			public int CompareTo(object obj)
			{
				if (obj == null) throw new ArgumentNullException("obj");
				if (!(obj is Acceleration<T, C>)) throw new ArgumentException("Expected type Acceleration.", "obj");
				return CompareTo((Acceleration<T, C>) obj);
			}

			// Windows Runtime Component does not allow public methods/ctors with same number of parameters: https://msdn.microsoft.com/en-us/library/br230301.aspx#Overloaded methods
#if WINDOWS_UWP
			internal
#else
			public
#endif
			int CompareTo(Acceleration<T, C> other)
			{
				return _meterPerSecondSquared.CompareTo(other._meterPerSecondSquared);
			}

			// Windows Runtime Component does not allow operator overloads: https://msdn.microsoft.com/en-us/library/br230301.aspx
#if !WINDOWS_UWP
			public static bool operator <=(Acceleration<T, C> left, Acceleration<T, C> right)
			{
				return left._meterPerSecondSquared <= right._meterPerSecondSquared;
			}

			public static bool operator >=(Acceleration<T, C> left, Acceleration<T, C> right)
			{
				return left._meterPerSecondSquared >= right._meterPerSecondSquared;
			}

			public static bool operator <(Acceleration<T, C> left, Acceleration<T, C> right)
			{
				return left._meterPerSecondSquared < right._meterPerSecondSquared;
			}

			public static bool operator >(Acceleration<T, C> left, Acceleration<T, C> right)
			{
				return left._meterPerSecondSquared > right._meterPerSecondSquared;
			}

			[Obsolete("It is not safe to compare equality due to using System.Double as the internal representation. It is very easy to get slightly different values due to floating point operations. Instead use Equals(other, maxError) to provide the max allowed error.")]
        public static bool operator ==(Acceleration<T, C> left, Acceleration<T, C> right)
			{
				// ReSharper disable once CompareOfFloatsByEqualityOperator
				return left._meterPerSecondSquared == right._meterPerSecondSquared;
			}

			[Obsolete("It is not safe to compare equality due to using System.Double as the internal representation. It is very easy to get slightly different values due to floating point operations. Instead use Equals(other, maxError) to provide the max allowed error.")]
        public static bool operator !=(Acceleration<T, C> left, Acceleration<T, C> right)
			{
				// ReSharper disable once CompareOfFloatsByEqualityOperator
				return left._meterPerSecondSquared != right._meterPerSecondSquared;
			}
#endif

			[Obsolete("It is not safe to compare equality due to using System.Double as the internal representation. It is very easy to get slightly different values due to floating point operations. Instead use Equals(other, maxError) to provide the max allowed error.")]
        public override bool Equals(object obj)
			{
				if (obj == null || GetType() != obj.GetType())
				{
					return false;
				}

				return _meterPerSecondSquared.Equals(((Acceleration<T, C>) obj)._meterPerSecondSquared);
			}

			/// <summary>
			///     Compare equality to another Acceleration by specifying a max allowed difference.
			///     Note that it is advised against specifying zero difference, due to the nature
			///     of floating point operations and using System.Double internally.
			/// </summary>
			/// <param name="other">Other quantity to compare to.</param>
			/// <param name="maxError">Max error allowed.</param>
			/// <returns>True if the difference between the two values is not greater than the specified max.</returns>
			public bool Equals(Acceleration<T, C> other, Acceleration<T, C> maxError)
			{
				return Math.Abs((decimal)_meterPerSecondSquared - (decimal)other._meterPerSecondSquared) <= maxError._meterPerSecondSquared;
			}

			public override int GetHashCode()
			{
				return _meterPerSecondSquared.GetHashCode();
			}

			#endregion

			#region Conversion

			/// <summary>
			///     Convert to the unit representation <paramref name="unit" />.
			/// </summary>
			/// <returns>Value in new unit if successful, exception otherwise.</returns>
			/// <exception cref="NotImplementedException">If conversion was not successful.</exception>
			public Number<T, C> As(AccelerationUnit unit)
			{
				switch (unit)
				{
					case AccelerationUnit.CentimeterPerSecondSquared:
						return CentimeterPerSecondSquared;
					case AccelerationUnit.DecimeterPerSecondSquared:
						return DecimeterPerSecondSquared;
					case AccelerationUnit.FootPerSecondSquared:
						return FeetPerSecondSquared;
					case AccelerationUnit.InchPerSecondSquared:
						return InchesPerSecondSquared;
					case AccelerationUnit.KilometerPerSecondSquared:
						return KilometerPerSecondSquared;
					case AccelerationUnit.MeterPerSecondSquared:
						return MeterPerSecondSquared;
					case AccelerationUnit.MicrometerPerSecondSquared:
						return MicrometerPerSecondSquared;
					case AccelerationUnit.MillimeterPerSecondSquared:
						return MillimeterPerSecondSquared;
					case AccelerationUnit.NanometerPerSecondSquared:
						return NanometerPerSecondSquared;
					case AccelerationUnit.StandardGravity:
						return StandardGravity;

					default:
						throw new NotImplementedException("unit: " + unit);
				}
			}

			#endregion

			#region Parsing

			/// <summary>
			///     Parse a string with one or two quantities of the format "&lt;quantity&gt; &lt;unit&gt;".
			/// </summary>
			/// <param name="str">String to parse. Typically in the form: {number} {unit}</param>
			/// <example>
			///     Length.Parse("5.5 m", new CultureInfo("en-US"));
			/// </example>
			/// <exception cref="ArgumentNullException">The value of 'str' cannot be null. </exception>
			/// <exception cref="ArgumentException">
			///     Expected string to have one or two pairs of quantity and unit in the format
			///     "&lt;quantity&gt; &lt;unit&gt;". Eg. "5.5 m" or "1ft 2in"
			/// </exception>
			/// <exception cref="AmbiguousUnitParseException">
			///     More than one unit is represented by the specified unit abbreviation.
			///     Example: Volume.Parse("1 cup") will throw, because it can refer to any of
			///     <see cref="VolumeUnit.MetricCup" />, <see cref="VolumeUnit.UsLegalCup" /> and <see cref="VolumeUnit.UsCustomaryCup" />.
			/// </exception>
			/// <exception cref="UnitsNetException">
			///     If anything else goes wrong, typically due to a bug or unhandled case.
			///     We wrap exceptions in <see cref="UnitsNetException" /> to allow you to distinguish
			///     Units.NET exceptions from other exceptions.
			/// </exception>
			public static Acceleration<T, C> Parse(string str)
			{
				return Parse(str, null);
			}

			/// <summary>
			///     Parse a string with one or two quantities of the format "&lt;quantity&gt; &lt;unit&gt;".
			/// </summary>
			/// <param name="str">String to parse. Typically in the form: {number} {unit}</param>
			/// <param name="culture">Format to use when parsing number and unit. If it is null, it defaults to <see cref="NumberFormatInfo.CurrentInfo"/> for parsing the number and <see cref="CultureInfo.CurrentUICulture"/> for parsing the unit abbreviation by culture/language.</param>
			/// <example>
			///     Length.Parse("5.5 m", new CultureInfo("en-US"));
			/// </example>
			/// <exception cref="ArgumentNullException">The value of 'str' cannot be null. </exception>
			/// <exception cref="ArgumentException">
			///     Expected string to have one or two pairs of quantity and unit in the format
			///     "&lt;quantity&gt; &lt;unit&gt;". Eg. "5.5 m" or "1ft 2in"
			/// </exception>
			/// <exception cref="AmbiguousUnitParseException">
			///     More than one unit is represented by the specified unit abbreviation.
			///     Example: Volume.Parse("1 cup") will throw, because it can refer to any of
			///     <see cref="VolumeUnit.MetricCup" />, <see cref="VolumeUnit.UsLegalCup" /> and <see cref="VolumeUnit.UsCustomaryCup" />.
			/// </exception>
			/// <exception cref="UnitsNetException">
			///     If anything else goes wrong, typically due to a bug or unhandled case.
			///     We wrap exceptions in <see cref="UnitsNetException" /> to allow you to distinguish
			///     Units.NET exceptions from other exceptions.
			/// </exception>
			public static Acceleration<T, C> Parse(string str, [CanBeNull] Culture culture)
			{
				if (str == null) throw new ArgumentNullException("str");

			// Windows Runtime Component does not support CultureInfo type, so use culture name string for public methods instead: https://msdn.microsoft.com/en-us/library/br230301.aspx
#if WINDOWS_UWP
				IFormatProvider formatProvider = culture == null ? null : new CultureInfo(culture);
#else
				IFormatProvider formatProvider = culture;
#endif
					return QuantityParser.Parse<Acceleration<T, C>, AccelerationUnit>(str, formatProvider,
					delegate(string value, string unit, IFormatProvider formatProvider2)
					{
						double parsedValue = double.Parse(value, formatProvider2);
						AccelerationUnit parsedUnit = ParseUnit(unit, formatProvider2);
						return From(new C().ConvertToNumber(parsedValue), parsedUnit);
					}, (x, y) => FromMeterPerSecondSquared((Number<T, C>)x.MeterPerSecondSquared + y.MeterPerSecondSquared));
			}

			/// <summary>
			///     Try to parse a string with one or two quantities of the format "&lt;quantity&gt; &lt;unit&gt;".
			/// </summary>
			/// <param name="str">String to parse. Typically in the form: {number} {unit}</param>
			/// <param name="result">Resulting unit quantity if successful.</param>
			/// <example>
			///     Length.Parse("5.5 m", new CultureInfo("en-US"));
			/// </example>
			public static bool TryParse([CanBeNull] string str, out Acceleration<T, C> result)
			{
				return TryParse(str, null, out result);
			}

			/// <summary>
			///     Try to parse a string with one or two quantities of the format "&lt;quantity&gt; &lt;unit&gt;".
			/// </summary>
			/// <param name="str">String to parse. Typically in the form: {number} {unit}</param>
			/// <param name="culture">Format to use when parsing number and unit. If it is null, it defaults to <see cref="NumberFormatInfo.CurrentInfo"/> for parsing the number and <see cref="CultureInfo.CurrentUICulture"/> for parsing the unit abbreviation by culture/language.</param>
			/// <param name="result">Resulting unit quantity if successful.</param>
			/// <example>
			///     Length.Parse("5.5 m", new CultureInfo("en-US"));
			/// </example>
			public static bool TryParse([CanBeNull] string str, [CanBeNull] Culture culture, out Acceleration<T, C> result)
			{
				try
				{
					result = Parse(str, culture);
					return true;
				}
				catch
				{
					result = default(Acceleration<T, C>);
					return false;
				}
			}

			/// <summary>
			///     Parse a unit string.
			/// </summary>
			/// <example>
			///     Length.ParseUnit("m", new CultureInfo("en-US"));
			/// </example>
			/// <exception cref="ArgumentNullException">The value of 'str' cannot be null. </exception>
			/// <exception cref="UnitsNetException">Error parsing string.</exception>
			public static AccelerationUnit ParseUnit(string str)
			{
				return ParseUnit(str, (IFormatProvider)null);
			}

			/// <summary>
			///     Parse a unit string.
			/// </summary>
			/// <example>
			///     Length.ParseUnit("m", new CultureInfo("en-US"));
			/// </example>
			/// <exception cref="ArgumentNullException">The value of 'str' cannot be null. </exception>
			/// <exception cref="UnitsNetException">Error parsing string.</exception>
			public static AccelerationUnit ParseUnit(string str, [CanBeNull] string cultureName)
			{
				return ParseUnit(str, cultureName == null ? null : new CultureInfo(cultureName));
			}

			/// <summary>
			///     Parse a unit string.
			/// </summary>
			/// <example>
			///     Length.ParseUnit("m", new CultureInfo("en-US"));
			/// </example>
			/// <exception cref="ArgumentNullException">The value of 'str' cannot be null. </exception>
			/// <exception cref="UnitsNetException">Error parsing string.</exception>

			// Windows Runtime Component does not allow public methods/ctors with same number of parameters: https://msdn.microsoft.com/en-us/library/br230301.aspx#Overloaded methods
#if WINDOWS_UWP
			internal
#else
			public
#endif
			static AccelerationUnit ParseUnit(string str, IFormatProvider formatProvider = null)
			{
				if (str == null) throw new ArgumentNullException("str");

				var unitSystem = UnitSystem.GetCached(formatProvider);
				var unit = unitSystem.Parse<AccelerationUnit>(str.Trim());

				if (unit == AccelerationUnit.Undefined)
				{
					var newEx = new UnitsNetException("Error parsing string. The unit is not a recognized AccelerationUnit.");
					newEx.Data["input"] = str;
					newEx.Data["formatprovider"] = formatProvider?.ToString() ?? "(null)";
					throw newEx;
				}

				return unit;
			}

			#endregion

			/// <summary>
			///     Set the default unit used by ToString(). Default is MeterPerSecondSquared
			/// </summary>
			public static AccelerationUnit ToStringDefaultUnit { get; set; } = AccelerationUnit.MeterPerSecondSquared;

			/// <summary>
			///     Get default string representation of value and unit.
			/// </summary>
			/// <returns>String representation.</returns>
			public override string ToString()
			{
				return ToString(ToStringDefaultUnit);
			}

			/// <summary>
			///     Get string representation of value and unit. Using current UI culture and two significant digits after radix.
			/// </summary>
			/// <param name="unit">Unit representation to use.</param>
			/// <returns>String representation.</returns>
			public string ToString(AccelerationUnit unit)
			{
				return ToString(unit, null, 2);
			}

			/// <summary>
			///     Get string representation of value and unit. Using two significant digits after radix.
			/// </summary>
			/// <param name="unit">Unit representation to use.</param>
			/// <param name="culture">Culture to use for localization and number formatting.</param>
			/// <returns>String representation.</returns>
			public string ToString(AccelerationUnit unit, [CanBeNull] Culture culture)
			{
				return ToString(unit, culture, 2);
			}

			/// <summary>
			///     Get string representation of value and unit.
			/// </summary>
			/// <param name="unit">Unit representation to use.</param>
			/// <param name="culture">Culture to use for localization and number formatting.</param>
			/// <param name="significantDigitsAfterRadix">The number of significant digits after the radix point.</param>
			/// <returns>String representation.</returns>
			[UsedImplicitly]
			public string ToString(AccelerationUnit unit, [CanBeNull] Culture culture, int significantDigitsAfterRadix)
			{
				Number<T, C>  value = As(unit);
				string format = UnitFormatter.GetFormat((double)value, significantDigitsAfterRadix);
				return ToString(unit, culture, format);
			}

			/// <summary>
			///     Get string representation of value and unit.
			/// </summary>
			/// <param name="culture">Culture to use for localization and number formatting.</param>
			/// <param name="unit">Unit representation to use.</param>
			/// <param name="format">String format to use. Default:  "{0:0.##} {1} for value and unit abbreviation respectively."</param>
			/// <param name="args">Arguments for string format. Value and unit are implictly included as arguments 0 and 1.</param>
			/// <returns>String representation.</returns>
			[UsedImplicitly]
			public string ToString(AccelerationUnit unit, [CanBeNull] Culture culture, [NotNull] string format,
				[NotNull] params object[] args)
			{
				if (format == null) throw new ArgumentNullException(nameof(format));
				if (args == null) throw new ArgumentNullException(nameof(args));

			// Windows Runtime Component does not support CultureInfo type, so use culture name string for public methods instead: https://msdn.microsoft.com/en-us/library/br230301.aspx
#if WINDOWS_UWP
				IFormatProvider formatProvider = culture == null ? null : new CultureInfo(culture);
#else
				IFormatProvider formatProvider = culture;
#endif
				Number<T, C>  value = As(unit);
				object[] formatArgs = UnitFormatter.GetFormatArgs(unit, (double)value, formatProvider, args);
				return string.Format(formatProvider, format, formatArgs);
			}

			/// <summary>
			/// Represents the largest possible value of Acceleration
			/// </summary>
			public static Number<T, C> MaxValue
			{
				get
				{
					return Number<T, C>.MaxValue;
				}
			}

			/// <summary>
			/// Represents the smallest possible value of Acceleration
			/// </summary>
			public static Number<T, C> MinValue
			{
				get
				{
					return Number<T, C>.MinValue;
				}
			}
		}
	}
}
